[functions]
  [functions.get-custom-claims]
    handler = "index.handler"
    runtime = "deno"
    verify_jwt = true

[auth.hook]
get_custom_claims = "http://localhost:54321/functions/v1/get-custom-claims"
